"""empty message

Revision ID: 848877345e9d
Revises: 02e7c13431bb
Create Date: 2020-08-25 21:06:25.991761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848877345e9d'
down_revision = '02e7c13431bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
