"""empty message

Revision ID: 940b1463f93f
Revises: 848877345e9d
Create Date: 2020-08-25 22:05:02.771838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940b1463f93f'
down_revision = '848877345e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
